capsulefyweb/capsulefyweb/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth import views as auth_views
from main import views, views_user, views_admin
from main.admin import admin_site

handler404 = 'main.views_error.handler404'

urlpatterns = [
    path('', views.index),
    path('admin/', admin_site.urls),
    path('displaycapsule/<int:id>/', views.displayCapsules, name='displaycapsule'),
    path('list/<str:type>/', views.list,  name='list'),
    path('newmodularcapsule/', login_required(views.createModularCapsule), name='createmodularcapsule'),
    path('newmodule/<int:pk>/', login_required(views.createModule), name='createmodule'),
    path('editmodularcapsule/<int:pk>/', login_required(views.editModularCapsule), name='editmodularcapsule'),
    path('editmodule/<int:pk>/', login_required(views.editModule), name='editmodule'),
    path('deletemodule/<int:pk>/', login_required(views.deleteModule), name='deletemodule'),
    path('newfreecapsule/', views.createFreeCapsule, name='createfreecapsule'),
    path('editfreecapsule/<int:pk>/', views.editFreeCapsule, name='editfreecapsule'),
    path('deletecapsule/<int:pk>/', views.deleteCapsule, name='deletecapsule'),
    path('deletefile/<int:pk>/', views.deleteFile, name='deletefile'),
    path('deletefreefile/<int:pk>/', views.deleteFreeFile, name='deletefreefile'),
    path('login/', views.login.as_view(),name='login'),
    path('accounts/login/', views.login.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('select_capsule/', views.select_capsule),
    path('refresh/<int:id>/', views.refresh_deadman, name='refreshdeadman'),
    path('ajaxlist/<str:type>', views.ajaxlist),
    path('register/', views_user.register),
    path('payment/execute/', views.paymentExecute),
    path('user/myaccount/', views.my_account, name='myaccount'),
    path('user/logintwitter/', views.login_twitter, name='logintwitter'),
    path('user/successtwitter/', views.success_twitter, name='successtwitter'),
    path('adm/list/', views_admin.list),
    path('adm/dashboard/', views_admin.dashboard),
    path('ajaxban/', views_admin.ajax_ban),
    path('update/', views.update,name='update'),
    path('deleteUser/', views_user.deleteUser),
    path('user/notifemail/', views.update_notifemail, name='notifemail'),
    path('terms', views.terms,name='terms'),
    path('user/changepassword/', views_user.change_password,name='change_password'),
]

capsulefyweb/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


from datetime import timezone, datetime
from django.core.exceptions import ValidationError



# Create your models here.
def birthdate_validator(value):
        
        if value >= datetime.now(timezone.utc).date():
            raise ValidationError('The birthdate must be in the past')
       
class Actor(User):
     
    birthdate=models.DateField(validators=[birthdate_validator,])
    class Meta:
        abstract = True

class User(Actor):
    email_notification=models.EmailField(blank=True)
    '''
    def clean(self):
        if not re.match(r'^(?=.*[a-z])(?=.*?[A-Z])(?=.*\d)[A-Za-z\d@$!¡¿?/%*#?&.:,;Çç\-*+\\<>]{8,}$', self.password):
            raise ValidationError({'password': ValidationError('Password incorrect, at least 8 characters, one number, one capital letter, one small letter '+\
                                                           ' (Optinal allow: @$!¡¿?/%*#?&.:,;Çç-*+\<>).'),})
     '''       

class Social_network(models.Model):
    social_type=models.CharField(max_length=1,choices=(('F','FACEBOOK'),('T','TWITTER')))
    token=models.CharField(max_length=100)
    secret=models.CharField(max_length=100,null=True)
    user=models.ForeignKey(User,related_name='social_networks', on_delete=CASCADE)
    
    
class Admin(Actor):
    pass

class Capsule(models.Model):
    creation_date=models.DateTimeField(auto_now_add=True)
    title=models.CharField(max_length=250)
    emails=models.CharField(blank=True, null=True, max_length=2500)
    capsule_type=models.CharField(max_length=1,choices=(('F','FREE'),('P','PREMIUM'),('M','MODULAR')))
    private=models.BooleanField()
    price=models.DecimalField(null=True,max_digits=7, decimal_places=2)
    dead_man_switch=models.BooleanField()
    dead_man_counter=models.BigIntegerField()
    dead_man_initial_counter=models.BigIntegerField()
    time_unit=models.IntegerField(null=True,choices=((0,'minutes'),(1,'days'),(2,'months'),(3,'years')))
    twitter=models.BooleanField()
    facebook=models.BooleanField()
    creator=models.ForeignKey(User,related_name='capsuls', on_delete=CASCADE)
    payment_id=models.CharField(max_length=60,null=True)
    expiration_notify = models.BooleanField(default=False)
    ''' Una capsula es liberada si tiene algún 
    modulo que este liberado '''
    @property
    def is_released(self):
        res=False
        for i in self.modules.all():
            if(i.is_released):
                res=True
                break
        return res

    def seconds_to_unit(self):
        conversion_to_seconds = [60, 86400, 2592000, 31536000]
        if self.time_unit!=None:
            res=round(self.dead_man_counter/conversion_to_seconds[int(self.time_unit)])
        else:
            res=0
        return res

    def unit_to_seconds(self,unit):
        conversion_to_seconds = [60, 86400, 2592000, 31536000]
        if unit!=None:
            res=self.dead_man_counter*conversion_to_seconds[unit]
        else:
            res=0
        return res
class Module(models.Model):
    description=models.CharField(max_length=250)
    release_date=models.DateTimeField()
    capsule=models.ForeignKey(Capsule,related_name='modules', on_delete=CASCADE)
    release_notify=models.BooleanField(default=False)
    facebook_notify = models.BooleanField(default=False)
    twitter_notify = models.BooleanField(default=False)
    @property
    def is_released(self):
        return datetime.now(timezone.utc) >= self.release_date
    
class File(models.Model):
    url=models.URLField()
    size=models.DecimalField(null=True,max_digits=7, decimal_places=2)
    type=models.CharField(max_length=1,choices=(('F','FILE'),('I','IMAGE'),('V','VIDEO')))
    remote_name=models.CharField(max_length=150)
    local_name=models.CharField(max_length=150)
    module=models.ForeignKey(Module, related_name='files', on_delete=CASCADE)

capsulefyweb/main/views.py
import paypalrestsdk
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, HttpResponse
from django.db.models import Q
from main import paypal
from .forms import ContactForm, NewFreeCapsuleForm, EditFreeCapsuleForm, ModularCapsuleForm, ModuleForm,\
    ModulesFormSet, NotifEmailForm
from .models import Capsule, Module, File, Social_network, User, Admin
from gcloud import storage
from oauth2client.service_account import ServiceAccountCredentials
from django.conf import settings
from random import randint
import os
from datetime import datetime, timezone
from django.http import HttpResponseNotFound
import smtplib
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
import mimetypes
import main
from apscheduler.schedulers.background import BackgroundScheduler
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.template.loader import render_to_string
import tweepy
from _functools import reduce
import operator

from main.logic import check_modules_release, remove_expired_capsules, check_deadman_switch, upload_file, \
    checkModuleFiles, checkSize, delete_files, delete_file

from main.logic import check_modules_release,remove_expired_capsules,check_deadman_switch
from django.contrib import messages


def index(request):
    return render(request, 'index.html')


def displayCapsules(request, id):
    capsule = get_object_or_404(Capsule, id=id)
    if capsule.capsule_type == 'M' and capsule.payment_id is None:
        return HttpResponseNotFound()
    creator = False
    editable = True
    if request.user.is_authenticated:
        user = request.user
        if user.id == capsule.creator.id:
            creator = True
    modules = []
    for module in capsule.modules.all():
        if module.release_date < datetime.now(timezone.utc):
            editable = False
        if not (creator == False and module.release_date > datetime.now(timezone.utc)):
            modules.append(module)
    modules.sort(key=lambda x: x.pk)

    urlBack = request.META.get('HTTP_REFERER')
    if urlBack == None:
        urlBack = '/list/public'
    elif not ('/list/public' in urlBack) and not ('/list/private' in urlBack):
        if(request.user.is_authenticated):
            urlBack = '/list/private'
        else:
            urlBack = '/list/public' 

    if len(modules) == 0:
        return HttpResponseNotFound()
    else:
        return render(request, 'capsule/displaycapsule.html', {'urlBack': urlBack, 'capsule': capsule, 'modules': modules, 'editable': editable})


conversion_to_seconds = [60, 86400, 2592000, 31536000]

testMode = False
def createModularCapsule(request):
    user = request.user
    if user.is_superuser:
        return HttpResponseNotFound()
    errors = []
    if request.method == 'POST':
        capsuleForm = ModularCapsuleForm(request.POST, user=request.user)
        moduleFormSet = ModulesFormSet(request.POST,  request.FILES)
        size = checkSize(request, moduleFormSet)
        if size > 524288000:
            errors.append("The total size of files can not be more than 500mb ")
        if capsuleForm.is_valid() and moduleFormSet.is_valid() and len(errors) == 0:
            title = capsuleForm.cleaned_data['title']
            emails = capsuleForm.cleaned_data['emails']
            capsule_type = 'M'
            private = capsuleForm.cleaned_data['private']
            try:
                time_unit = int(capsuleForm.cleaned_data['deadman_time_unit'])
                dead_man_switch = capsuleForm.cleaned_data['deadman_switch']
                dead_man_counter = capsuleForm.cleaned_data['deadman_counter'] * conversion_to_seconds[time_unit]
            except:
                dead_man_switch = False
                dead_man_counter = 0
                time_unit = 0
            price = 11.99
            twitter = capsuleForm.cleaned_data['twitter']
            facebook = capsuleForm.cleaned_data['facebook']
            capsule = Capsule.objects.create(title=title, emails=emails, capsule_type=capsule_type, private=private,
                                             dead_man_switch=dead_man_switch, dead_man_counter=dead_man_counter,
                                             dead_man_initial_counter=dead_man_counter, time_unit=time_unit,
                                             twitter=twitter, facebook=facebook,
                                             creator_id=user.id, price=price)
            modulesCount = 0;
            for moduleForm in moduleFormSet:
                description = moduleForm.cleaned_data['description']
                release_date = moduleForm.cleaned_data['release_date']
                files = request.FILES.getlist('form-' + str(modulesCount) + '-file')
                module = Module.objects.create(description=description, release_date=release_date,
                                               capsule_id=capsule.id)
                modulesCount += 1
                if files is not None:
                    for file in files:
                        upload_file(capsule, module, file)
            if not testMode:
                request.session['capsuleId'] = capsule.id
                request.session.modified = True
                approval_url = paypal.payment(capsule.id)
                return HttpResponseRedirect(approval_url)
            else:
                return HttpResponseRedirect('/displaycapsule/' + str(capsule.id))
    else:
        capsuleForm = ModularCapsuleForm()
        moduleFormSet = ModulesFormSet()
    return render(request, 'capsule/createmodularcapsule.html', {"capsuleForm": capsuleForm, "moduleFormSet": moduleFormSet, "errors": errors})


def paymentExecute(request):
    paymentId = request.GET["paymentId"]
    PayerID = request.GET["PayerID"]
    payment = paypalrestsdk.Payment.find(paymentId)
    paypal.execute(payment, PayerID)
    capsuleId = request.session['capsuleId']
    capsule = Capsule.objects.filter(id=capsuleId).first()
    capsule.payment_id = paymentId
    capsule.save()
    return HttpResponseRedirect('/displaycapsule/' + str(capsuleId))


def editModularCapsule(request, pk):
    oldcapsule = get_object_or_404(Capsule, id=pk)
    if (oldcapsule.capsule_type != "M"):
        return HttpResponseNotFound()
    user = request.user
    if user.id != oldcapsule.creator.id:
        return HttpResponseNotFound()
    for module in oldcapsule.modules.all():
        if module.release_date < datetime.now(timezone.utc):
            return HttpResponseNotFound()
    olddata = {
        'title': oldcapsule.title,
        'emails': oldcapsule.emails,
        'twitter': oldcapsule.twitter,
        'facebook': oldcapsule.facebook,
        'private': oldcapsule.private,
        'deadman_switch': oldcapsule.dead_man_switch,
        'deadman_counter': oldcapsule.seconds_to_unit(),
        'deadman_time_unit': oldcapsule.time_unit
    }
    if request.method == 'POST':
        form = ModularCapsuleForm(request.POST, user=request.user)
        if form.is_valid():
            formulario = form.cleaned_data
            oldcapsule.title = formulario['title']
            oldcapsule.emails = formulario['emails']
            oldcapsule.twitter = formulario['twitter']
            oldcapsule.facebook = formulario['facebook']
            oldcapsule.private = formulario['private']
            try:
                time_unit = int(formulario['deadman_time_unit'])
                oldcapsule.time_unit=time_unit
                oldcapsule.dead_man_switch = formulario['deadman_switch']
                oldcapsule.dead_man_counter = formulario['deadman_counter']*conversion_to_seconds[time_unit]
                oldcapsule.dead_man_initial_counter = formulario['deadman_counter'] * conversion_to_seconds[time_unit]
            except:
                dead_man_switch = False
                dead_man_counter = 0
                time_unit = 0
            oldcapsule.save()
            return HttpResponseRedirect('/displaycapsule/' + str(pk))
    else:
        form = ModularCapsuleForm(initial=olddata)
    return render(request, 'capsule/editmodularcapsule.html', {'form': form, 'oldcapsule': oldcapsule})


def createModule(request, pk):
    user = request.user
    capsule = get_object_or_404(Capsule, id=pk)
    if user.id != capsule.creator.id:
        return HttpResponseNotFound()
    errors = []
    if request.method == 'POST':
        moduleForm = ModuleForm(request.POST, request.FILES)
        errors = checkModuleFiles(request, capsule)
        if moduleForm.is_valid() and len(errors) == 0:
            moduleFormulario = moduleForm.cleaned_data
            description = moduleFormulario['description']
            release_date = moduleFormulario['release_date']
            module = Module.objects.create(description=description, release_date=release_date, capsule_id=pk)
            files = request.FILES.getlist('file')
            if files is not None:
                for file in files:
                    upload_file(module.capsule, module, file)
            return HttpResponseRedirect('/editmodularcapsule/' + str(pk))
    else:
        moduleForm = ModuleForm()
    return render(request, 'capsule/editmodule.html', {'form': moduleForm, 'capsuleID': capsule.id, 'type': 'create', 'errors': errors})


def editModule(request, pk):
    oldmodule = get_object_or_404(Module, id=pk)
    errors = []
    if (oldmodule.capsule.capsule_type != "M"):
        return HttpResponseNotFound()
    if oldmodule.release_date < datetime.now(timezone.utc):
        return HttpResponseNotFound()
    user = request.user
    if user.id != oldmodule.capsule.creator.id:
        return HttpResponseNotFound()
    olddata = {
        'description': oldmodule.description,
        'release_date': str(oldmodule.release_date.date()),
    }
    if request.method == 'POST':
        form = ModuleForm(request.POST, request.FILES)
        errors = checkModuleFiles(request, oldmodule.capsule)

capsulefyweb/main/templates/user/change_password.html
{% extends 'base.html' %}
{% block contenido %}
{% load static %}
<script>
function checkPassword(){
	p1=$("#id_password").val()
	p2=$("#id_password2").val()
	
	
	if(p1!=p2){
		$("#id_error_p").html("Passwords don't match.")
		return false;
	}else{
		$("#id_error_p").html("")
		return true;
	}
}

</script>
<div class="container">
    <form action="" method="post" class="needs-validation" novalidate onsubmit="return checkPassword();">
        <h3 class="title">Change my password</h3>
		<hr>
    	    {% csrf_token %}
    	    <div class="form-group">
		    <label for="id_old_pass"><span class="red" >*</span> 
		    		Old Password {{ form.old_pass.errors }}
		    		<span id="id_old_pass" class="red"></span>
		    	</label>
		    <input type="password"  class="form-control" name="old_pass" 
		    	id="id_old_pass" maxlength="128" 
		    	value="" required placeholder="Old password">
		</div>
		<div class="form-group">
		    <label for="id_password"><span class="red" >*</span> 
		    		Password {{ form.password.errors }}
		    		<span id="id_error_p" class="red"></span>
		    	</label>
		    <input type="password" onkeyup="checkPassword()" class="form-control" name="password" 
		    	id="id_password" maxlength="128" 
		    	value="" required placeholder="New password">
		</div>
		<div class="form-group">
		    <label for="id_password"><span class="red">*</span> 
		    		Repeat password {{ form.password.errors }}
		    	</label>
		    <input onkeyup="checkPassword()" type="password" class="form-control" name="password" 
		    	id="id_password2" maxlength="128" 
		    	value="" required placeholder="Repeat new password">
		</div>

			<button type="submit" value="submit" class="btn btn-primary">Submit</button>
			<button type="button" class="btn btn-secondary" onclick="window.location = '/user/myaccount'">Cancel</button>
    </form>
</div>

{% endblock %}
{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styleForm.css' %}"/>
{% endblock %}

capsulefyweb/main/templates/user/myaccount.html
{% extends 'base.html' %}
{% block contenido %}
{% load static %}
  <main>
  <div class="container">
    <div>
      <h2 class="title">My account</h2><hr>
    </div>
  </div>
  <div class="container">
    <div class="row">  
      <div class="a col-sm-12 col-md-9">
        <h3 class="name">{{user.get_full_name}}</h3>
        <p><b>Username: </b> {{user.get_username}}</p>
        <p><b>Birthdate: </b>{{userlogged.birthdate}}</p>
        <p><b>Email:</b> {{userlogged.email}}</p>
        {% if userlogged.email_notification != "" %}
          <p><b>Email for notifications: </b> {{userlogged.email_notification}}</p> 
        {% endif %}
        <hr>
        <div id="buttonrow" class="row justify-content-between">
          <div class="col">
            <button class="btn btn-secondary" onclick="window.location='/'">Back</button>
            <button class="btn btn-primary" onclick="window.location='/user/notifemail'">Edit email for notifications</button>
          	
          </div>
          <div class="col">
          	<button class="btn btn-primary" onclick="window.location='/user/changepassword'">Change password</button>
          
            <button class="btn btn-danger" onClick="confirmAlert('Are you sure you want to delete your account?', '/deleteUser')">Delete account</button>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-3">
        {% if hastwitter %}
          <div class="container">
            <div class="row">
              <div style="padding-right:0" class="col-sm-3">
                <img src="{% static 'image/twitter-icon.png '%}" class="img-fluid" alt="Twitter icon">
              </div>
              <div class="col-sm-9" style="margin:auto"> Logged in as {{username}}</div>
            </div>
          </div>
        {% else %}
          <a href="/user/logintwitter"><img src="{% static 'image/twitter-login.png '%}" class="img-fluid" alt="Twitter login"></a>
        {% endif %}
      </div>
    </div>
  </div>
  </main>
  <br><br>
  <script>
  function confirmAlert(message, url){
    if(confirm(message)){
      window.location = url;
    }
  }
  </script>
{% endblock %}
{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styleAccount.css' %}"/>
{% endblock %}

capsulefyweb/main/templates/user/notifemail.html
{% extends 'base.html' %}
{% block contenido %}
{% load static %}

<div class="container">
    <form action="" method="post" class="needs-validation" novalidate>
        <h3 class="title">Editing notification email</h3>
		<hr>
    	    {% csrf_token %}
			<div class="form-group">
			    <label for="id_title">Email {{ form.email_notification.errors }}</label>
			    <input type="email" class="form-control" name="email_notification" id="id_email_notification" maxlength="250" value="{% if form.email_notification.value != None %}{{form.email_notification.value}}{% endif %}" required placeholder="Email">
			</div>

			<button type="submit" value="submit" class="btn btn-primary">Submit</button>
			<button type="button" class="btn btn-secondary" onclick="window.location = '/user/myaccount'">Cancel</button>
    </form>
</div>

{% endblock %}
{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styleForm.css' %}"/>
{% endblock %}