capsulefyweb/capsulefyweb/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.contrib.auth import views as auth_views
from main import views, views_user, views_admin
from main.admin import admin_site

handler404 = 'main.views_error.handler404'

urlpatterns = [
    path('', views.index),
    path('admin/', admin_site.urls),
    path('displaycapsule/<int:id>/', views.displayCapsules, name='displaycapsule'),
    path('list/<str:type>/', views.list,  name='list'),
    path('newmodularcapsule/', login_required(views.createModularCapsule), name='createmodularcapsule'),
    path('newmodule/<int:pk>/', login_required(views.createModule), name='createmodule'),
    path('editmodularcapsule/<int:pk>/', login_required(views.editModularCapsule), name='editmodularcapsule'),
    path('editmodule/<int:pk>/', login_required(views.editModule), name='editmodule'),
    path('deletemodule/<int:pk>/', login_required(views.deleteModule), name='deletemodule'),
    path('newfreecapsule/', views.createFreeCapsule, name='createfreecapsule'),
    path('editfreecapsule/<int:pk>/', views.editFreeCapsule, name='editfreecapsule'),
    path('deletecapsule/<int:pk>/', views.deleteCapsule, name='deletecapsule'),
    path('deletefile/<int:pk>/', views.deleteFile, name='deletefile'),
    path('deletefreefile/<int:pk>/', views.deleteFreeFile, name='deletefreefile'),
    path('login/', views.login.as_view(),name='login'),
    path('accounts/login/', views.login.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('select_capsule/', views.select_capsule),
    path('refresh/<int:id>/', views.refresh_deadman, name='refreshdeadman'),
    path('ajaxlist/<str:type>', views.ajaxlist),
    path('register/', views_user.register),
    path('payment/execute/', views.paymentExecute),
    path('user/myaccount/', views.my_account, name='myaccount'),
    path('user/logintwitter/', views.login_twitter, name='logintwitter'),
    path('user/successtwitter/', views.success_twitter, name='successtwitter'),
    path('adm/list/', views_admin.list),
    path('adm/dashboard/', views_admin.dashboard),
    path('ajaxban/', views_admin.ajax_ban),
    path('update/', views.update,name='update'),
    path('deleteUser/', views_user.deleteUser),
    path('user/notifemail/', views.update_notifemail, name='notifemail'),
    path('terms', views.terms,name='terms'),
    path('user/changepassword/', views_user.change_password,name='change_password'),
]

capsulefyweb/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE


from datetime import timezone, datetime
from django.core.exceptions import ValidationError



# Create your models here.
def birthdate_validator(value):
        
        if value >= datetime.now(timezone.utc).date():
            raise ValidationError('The birthdate must be in the past')
       
class Actor(User):
     
    birthdate=models.DateField(validators=[birthdate_validator,])
    class Meta:
        abstract = True

class User(Actor):
    email_notification=models.EmailField(blank=True)
    '''
    def clean(self):
        if not re.match(r'^(?=.*[a-z])(?=.*?[A-Z])(?=.*\d)[A-Za-z\d@$!¡¿?/%*#?&.:,;Çç\-*+\\<>]{8,}$', self.password):
            raise ValidationError({'password': ValidationError('Password incorrect, at least 8 characters, one number, one capital letter, one small letter '+\
                                                           ' (Optinal allow: @$!¡¿?/%*#?&.:,;Çç-*+\<>).'),})
     '''       

class Social_network(models.Model):
    social_type=models.CharField(max_length=1,choices=(('F','FACEBOOK'),('T','TWITTER')))
    token=models.CharField(max_length=100)
    secret=models.CharField(max_length=100,null=True)
    user=models.ForeignKey(User,related_name='social_networks', on_delete=CASCADE)
    
    
class Admin(Actor):
    pass

class Capsule(models.Model):
    creation_date=models.DateTimeField(auto_now_add=True)
    title=models.CharField(max_length=250)
    emails=models.CharField(blank=True, null=True, max_length=2500)
    capsule_type=models.CharField(max_length=1,choices=(('F','FREE'),('P','PREMIUM'),('M','MODULAR')))
    private=models.BooleanField()
    price=models.DecimalField(null=True,max_digits=7, decimal_places=2)
    dead_man_switch=models.BooleanField()
    dead_man_counter=models.BigIntegerField()
    dead_man_initial_counter=models.BigIntegerField()
    time_unit=models.IntegerField(null=True,choices=((0,'minutes'),(1,'days'),(2,'months'),(3,'years')))
    twitter=models.BooleanField()
    facebook=models.BooleanField()
    creator=models.ForeignKey(User,related_name='capsuls', on_delete=CASCADE)
    payment_id=models.CharField(max_length=60,null=True)
    expiration_notify = models.BooleanField(default=False)
    ''' Una capsula es liberada si tiene algún 
    modulo que este liberado '''
    @property
    def is_released(self):
        res=False
        for i in self.modules.all():
            if(i.is_released):
                res=True
                break
        return res

    def seconds_to_unit(self):
        conversion_to_seconds = [60, 86400, 2592000, 31536000]
        if self.time_unit!=None:
            res=round(self.dead_man_counter/conversion_to_seconds[int(self.time_unit)])
        else:
            res=0
        return res

    def unit_to_seconds(self,unit):
        conversion_to_seconds = [60, 86400, 2592000, 31536000]
        if unit!=None:
            res=self.dead_man_counter*conversion_to_seconds[unit]
        else:
            res=0
        return res
class Module(models.Model):
    description=models.CharField(max_length=250)
    release_date=models.DateTimeField()
    capsule=models.ForeignKey(Capsule,related_name='modules', on_delete=CASCADE)
    release_notify=models.BooleanField(default=False)
    facebook_notify = models.BooleanField(default=False)
    twitter_notify = models.BooleanField(default=False)
    @property
    def is_released(self):
        return datetime.now(timezone.utc) >= self.release_date
    
class File(models.Model):
    url=models.URLField()
    size=models.DecimalField(null=True,max_digits=7, decimal_places=2)
    type=models.CharField(max_length=1,choices=(('F','FILE'),('I','IMAGE'),('V','VIDEO')))
    remote_name=models.CharField(max_length=150)
    local_name=models.CharField(max_length=150)
    module=models.ForeignKey(Module, related_name='files', on_delete=CASCADE)

capsulefyweb/main/forms.py
import datetime
import re

from django import forms
from datetime import datetime, timedelta, timezone
from .models import File, Social_network, User
from django.db.models import Sum
from django.forms import formset_factory
from django.conf import settings
import tweepy


class ContactForm(forms.Form):
    Name = forms.CharField(max_length=50)
    Email = forms.EmailField()
    Message = forms.CharField(widget=forms.Textarea)


class ModularCapsuleForm(forms.Form):
    UNIT_CHOICES=((0,'minutes'),(1,'days'),(2,'months'),(3,'years'))
    title = forms.CharField(max_length=250)
    emails = forms.CharField(max_length=2500, required=False)
    twitter = forms.BooleanField(required=False)
    facebook = forms.BooleanField(required=False)
    private = forms.BooleanField(required=False)
    deadman_switch = forms.BooleanField(required=False)
    deadman_counter=forms.IntegerField(required=False)
    deadman_time_unit=forms.ChoiceField(required=False,choices=UNIT_CHOICES)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.upfiles = kwargs.pop('upfiles', None)
        super(ModularCapsuleForm, self).__init__(*args, **kwargs)

    def clean_twitter(self):
        data = self.cleaned_data['twitter']
        twitteracc = Social_network.objects.filter(social_type='T', user_id=self.user.id).first()
        if data:
            if twitteracc is not None:
                try:
                    consumer_secret = settings.TWITTER_CREDENTIALS['consumer_secret']
                    consumer_key = settings.TWITTER_CREDENTIALS['consumer_key']
                    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
                    auth.set_access_token(twitteracc.token, twitteracc.secret)
                    api = tweepy.API(auth)
                    api.me()
                except:
                    print('Twitter error, revoking credentials')
                    twitteracc.delete()
                    raise forms.ValidationError('You have no valid Twitter account')
            else:
                raise forms.ValidationError('You have no valid Twitter account')
        return data

    def clean_emails(self):
        emails = self.cleaned_data['emails']
        if emails != "":
            emailsList = emails.split(",")
            error = ""
            for i in range(len(emailsList)):
                match = re.search(r'\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b', emailsList[i], re.I)
                if match is None:
                    if len(error) == 0:
                        error += "Invalid email " + str(i + 1)
                    else:
                        error += ", invalid email " + str(i + 1)
            if len(error) != 0:
                raise forms.ValidationError(error)
        return emails

class ModuleForm(forms.Form):
    description = forms.CharField(max_length=250)
    release_date = forms.DateField()
    file = forms.FileField(required=False)

    def clean_release_date(self):
        data = self.cleaned_data['release_date']
        if data <= datetime.now(timezone.utc).date():
            raise forms.ValidationError('The release date must be in the future')
        return data


ModulesFormSet = formset_factory(ModuleForm, extra=1)


class NewFreeCapsuleForm(forms.Form):
    title = forms.CharField(max_length=250)
    description = forms.CharField(max_length=250)
    release_date = forms.DateField()
    emails = forms.CharField(max_length=2500, required=False)
    twitter = forms.BooleanField(required=False)
    facebook = forms.BooleanField(required=False)
    files = forms.FileField(required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.upfiles = kwargs.pop('upfiles', None)
        super(NewFreeCapsuleForm, self).__init__(*args, **kwargs)

    def clean_release_date(self):
        data = self.cleaned_data['release_date']
        if data <= datetime.now(timezone.utc).date():
            raise forms.ValidationError('The release date must be in the future')
        yearafter = datetime.now(timezone.utc).date() + timedelta(days=365)
        if data > yearafter:
            raise forms.ValidationError('The release date must be within 1 year from now')
        return data

    def clean_twitter(self):
        data = self.cleaned_data['twitter']
        twitteracc = Social_network.objects.filter(social_type='T', user_id=self.user.id).first()
        if data:
            if twitteracc is not None:
                try:
                    consumer_secret = settings.TWITTER_CREDENTIALS['consumer_secret']
                    consumer_key = settings.TWITTER_CREDENTIALS['consumer_key']
                    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
                    auth.set_access_token(twitteracc.token, twitteracc.secret)
                    api = tweepy.API(auth)
                    api.me()
                except:
                    print('Twitter error, revoking credentials')
                    twitteracc.delete()
                    raise forms.ValidationError('You have no valid Twitter account')
            else:
                raise forms.ValidationError('You have no valid Twitter account')
        return data

    def clean_files(self):
        data = self.upfiles
        files = File.objects.filter(module__capsule__capsule_type='F', module__capsule__creator_id=self.user.id).\
            aggregate(totalsum=Sum('size'))
        totalsum = 0.0
        if files['totalsum'] is not None:
            totalsum = float(files['totalsum'])
        if data is not None and data != []:
            for file in data:
                totalsum += (file.size / 1000000)
            if totalsum > 20.0:
                raise forms.ValidationError('You cannot store more than 20 MB using free capsules')
        return data

    def clean_emails(self):
        emails = self.cleaned_data['emails']
        if emails != "":
            emailsList = emails.split(",")
            error = ""
            for i in range(len(emailsList)):
                match = re.search(r'\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b', emailsList[i], re.I)
                if match is None:
                    if len(error) == 0:
                        error += "Invalid email " + str(i + 1)
                    else:
                        error += ", invalid email " + str(i + 1)
            if len(error) != 0:
                raise forms.ValidationError(error)
        return emails


class EditFreeCapsuleForm(forms.Form):
    title = forms.CharField(max_length=250)
    description = forms.CharField(max_length=250)
    release_date = forms.DateField()
    emails = forms.CharField(max_length=2500, required=False)
    twitter = forms.BooleanField(required=False)
    facebook = forms.BooleanField(required=False)
    files = forms.FileField(required=False)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        self.upfiles = kwargs.pop('upfiles', None)
        super(EditFreeCapsuleForm, self).__init__(*args, **kwargs)

    def clean_release_date(self):
        data = self.cleaned_data['release_date']
        if data <= datetime.now(timezone.utc).date():
            raise forms.ValidationError('The release date must be in the future')
        yearafter = datetime.now(timezone.utc).date() + timedelta(days=365)
        if data > yearafter:
            raise forms.ValidationError('The release date must be within 1 year from now')
        return data

    def clean_twitter(self):
        data = self.cleaned_data['twitter']
        twitteracc = Social_network.objects.filter(social_type='T', user_id=self.user.id).first()
        if data:
            if twitteracc is not None:
                try:
                    consumer_secret = settings.TWITTER_CREDENTIALS['consumer_secret']
                    consumer_key = settings.TWITTER_CREDENTIALS['consumer_key']
                    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
                    auth.set_access_token(twitteracc.token, twitteracc.secret)
                    api = tweepy.API(auth)
                    api.me()
                except:
                    print('Twitter error, revoking credentials')
                    twitteracc.delete()
                    raise forms.ValidationError('You have no valid Twitter account')
            else:
                raise forms.ValidationError('You have no valid Twitter account')
        return data

    def clean_files(self):
        data = self.upfiles
        files = File.objects.filter(module__capsule__capsule_type='F', module__capsule__creator_id=self.user.id).\
            aggregate(totalsum=Sum('size'))
        totalsum = 0.0
        if files['totalsum'] is not None:
            totalsum = float(files['totalsum'])
        if data is not None and data != []:
            for file in data:
                totalsum += (file.size / 1000000)
            if totalsum > 20.0:
                raise forms.ValidationError('You cannot store more than 20 MB using free capsules')
        return data

    def clean_emails(self):
        emails = self.cleaned_data['emails']
        if emails != "":
            emailsList = emails.split(",")
            error = ""
            for i in range(len(emailsList)):
                match = re.search(r'\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b', emailsList[i], re.I)
                if match is None:
                    if len(error) == 0:
                        error += "Invalid email " + str(i + 1)
                    else:
                        error += ", invalid email " + str(i + 1)
            if len(error) != 0:
                raise forms.ValidationError(error)
        return emails


class NotifEmailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email_notification',)

capsulefyweb/main/templates/capsule/createmodularcapsule.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}
    {% load static %}
    <div class="container">
        <form id="form" action="" method="post" onsubmit="submitEmail()" enctype="multipart/form-data">
            {% csrf_token %}
            <h3 class="title"> Creating a premium capsule</h3>
            <hr>
            {% for error in errors %}
                <p><b><span class="red">{{ error }}</span></b></p>
            {% endfor %}
            <div class="form-group">
                <label for="id_title"><span class="red">* </span>Title: {{ capsuleForm.title.errors }}</label>
                <input type="text" name="title" class="form-control"
                       value="{% if capsuleForm.title.value != None %}{{ capsuleForm.title.value }}{% endif %}"
                       maxlength="250" required id="id_title">
            </div>
            
            
            <div class="form-group">
			    <label>Emails {{ capsuleForm.emails.errors }}</label>
			    <div id="email_inputs">	
					</div>
					<button type="button" onclick="addEmail()" class="btn btn-success">Add email</button>
			</div>
			<input type="hidden" id="id_emails" name="emails">

            <p><b>{{capsuleForm.twitter.errors}}</b></p>
			{% if capsuleForm.twitter.value != None and capsuleForm.twitter.value == True %}
				<p><button type="button" onClick="add_twitter(this)" class="btn btn-success" id="twitter">Connected to twitter</button></p>
			{% else %}
				<p><button type="button" onClick="add_twitter(this)" class="btn btn-secondary" id="twitter">Connect to twitter?</button></p>
			{% endif %}
            <input style="display: none" type="checkbox" class="form-check-input" name="twitter" id="id_twitter"
                {% if capsuleForm.twitter.value == True %}checked{% endif %}>
                
            <hr>

            {% if capsuleForm.private.value != None and capsuleForm.private.value == True %}
                <p><button type="button" onClick="add_private(this)" class="btn btn-success" id="private">Private capsule</button></p>
            {% else %}
                <p><button type="button" onClick="add_private(this)" class="btn btn-secondary" id="private">Public capsule</button></p>
            {% endif %}
            <input style="display: none" type="checkbox" class="form-check-input" name="private" id="id_private"
                {% if capsuleForm.private.value == True %}checked{%endif%}>


            {% if capsuleForm.deadman_switch.value != None and capsuleForm.deadman_switch.value == True %}
                <p><button type="button" onClick="add_deadman_switch(this)" class="btn btn-success" id="deadman_switch">Deadman switch activated</button></p>
            {% else %}
                <p><button type="button" onClick="add_deadman_switch(this)" class="btn btn-secondary" id="deadman_swtich">Activate deadman switch?</button></p>
            {% endif %}
            <input style="display: none" type="checkbox" class="form-check-input" name="deadman_switch" id="id_deadman_switch"
                {% if capsuleForm.deadman_switch.value == True %}checked{%endif%}>



            <hr>
            <div id="input_deadman" style="display: none;">
                <div class="form-group row">
                    <label class="col-form-label col-sm-2" for="id_deadman_counter">Deadman timer:</label>
                    <div class="col-sm-2">
                        <input class="form-control" type="number" min="0" max="5000000000" name="deadman_counter"
                               id="id_deadman_counter"
                               value="{% if capsuleForm.deadman_counter.value != None %}{{capsuleForm.deadman_counter.value}}{% endif %}">
                    </div>
                    <div class="col-sm-2">
                        <select class="form-control" name="deadman_time_unit" id="id_deadman_time_unit">
                            <option value=0 {% if capsuleForm.deadman_time_unit.value == '0' %}selected{% endif %}>Minutes
                            </option>
                            <option value=1 {% if capsuleForm.deadman_time_unit.value == '1' %}selected{% endif %}>Days</option>
                            <option value=2 {% if capsuleForm.deadman_time_unit.value == '2' %}selected{% endif %}>Months
                            </option>
                            <option value=3 {% if capsuleForm.deadman_time_unit.value == '3' %}selected{% endif %}>Years
                            </option>
                        </select>
                    </div>
                </div>
                <hr>
            </div>
            {{ moduleFormSet.management_form }}
            <div class="modules" id="modules">
                {% for formModule in moduleFormSet %}
                    <div class="moduleform">
                        <div class="form-group">
                            <label for="id_form-{{ forloop.counter0 }}-description"><span class="red">* </span>Description: {{ formModule.description.errors }}
                            </label>
                            <textarea name="form-{{ forloop.counter0 }}-description" rows="5" maxlength="250" required
                                      class="form-control"
                                      id="id_form-{{ forloop.counter0 }}-description">{% if formModule.description.value != None %}{{ formModule.description.value }}{% endif %}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="id_form-{{ forloop.counter0 }}-release_date"><span class="red">* </span>Release
                                date: {{ formModule.release_date.errors }}</label>
                            <input type="date" name="form-{{ forloop.counter0 }}-release_date" required value="{% if formModule.release_date.value != None %}{{ formModule.release_date.value }}{% endif %}"
                                   class="form-control"
                                   id="id_form-{{ forloop.counter0 }}-release_date">
                        </div>
                        <div class="form-group">
                            <label for="id_form-{{ forloop.counter0 }}-file">File: {{ formModule.file.errors }}</label>
                            <input type="file" class="form-control-file" name="form-{{ forloop.counter0 }}-file"
                                   id="id_form-{{ forloop.counter0 }}-file"
                                   multiple>
                        </div>
                        {% if forloop.counter0 != 0 %}
                            <button type="button" class="btn btn-danger" onclick="removeModule(this)">Delete this module</button>
                        {% endif %}
                        <hr>
                    </div>
                {% endfor %}
            </div>
            <button class="btn btn-success" value="Add module" onclick="addModule()">Add module</button>
            <hr>
            <button class="btn btn-primary" type="submit" value="Pay capsule">Submit</button>
            <button type="button" class="btn btn-secondary" onclick="window.location='/'">Cancel</button>
            <br>
        </form>

    </div>

    <script>
        function addModule() {
            var div = document.createElement('div');
            var totalForms = parseInt(document.getElementById('id_form-TOTAL_FORMS').value);
            div.className = 'moduleform';
            div.innerHTML = `
                <h5 class="subtitle">Module ` + totalForms + `</h5>
                <div class="form-group">
                    <label for="id_form-` + totalForms + `-description"><span class="red">* </span>Description:</label>
                    <textarea name="form-` + totalForms + `-description" rows="5" maxlength="250" required class="form-control" id="id_form-` + totalForms + `-description"></textarea>
                </div>
                <div class="form-group">
                    <label for="id_form-` + totalForms + `-release_date"><span class="red">* </span>Release date:</label>
                    <input type="date" name="form-` + totalForms + `-release_date" required class="form-control" id="id_form-` + totalForms + `-release_date" placeholder="YYYY-MM-DD HH:MM">
                </div>
                <div class="form-group">
                    <label for="id_form-` + totalForms + `-file">File:</label>
                    <input type="file" class="form-control-file" name="form-` + totalForms + `-file" class="form-group-file" id="id_form-` + totalForms + `-file" multiple>
                </div>
                <button type="button" class="btn btn-danger" onclick="removeModule(this)">Delete this module</button>
                <hr>
            `;
            document.getElementById('modules').appendChild(div);
            document.getElementById('id_form-TOTAL_FORMS').value = totalForms + 1;
        }

        function removeModule(input) {
            document.getElementById('modules').removeChild(input.parentNode);
            var totalForms = parseInt(document.getElementById('id_form-TOTAL_FORMS').value);
            document.getElementById('id_form-TOTAL_FORMS').value = totalForms - 1;
        }

        function deadman_switch_activated() {
            var checkbox = document.getElementById("id_deadman_switch");
            if (checkbox.checked == true) {
                document.getElementById("input_deadman").style.display = "block";
            } else {
                document.getElementById("input_deadman").style.display = "none";
            }
        }
        deadman_switch_activated();


        if("{{capsuleForm.twitter.value}}" == "True"){
		    document.getElementById("id_twitter").setAttribute("checked", "checked");
	    }
    	function add_twitter(element){
	    	if(!document.getElementById("id_twitter").hasAttribute("checked")){
		    	document.getElementById("id_twitter").setAttribute("checked", "checked");
			    element.classList.remove("btn-secondary");
    			element.classList.add("btn-success");
	    		element.innerHTML = "Connected to Twitter";
		    }else{
    			document.getElementById("id_twitter").removeAttribute("checked");
	    		element.classList.remove("btn-success");
		    	element.classList.add("btn-secondary");
			    element.innerHTML = "Connect to Twitter?";
    		}
	    }
        if("{{capsuleForm.private.value}}" == "True"){
	        document.getElementById("id_private").setAttribute("checked", "checked");
	    }
        function add_private(element){
            if(!document.getElementById("id_private").hasAttribute("checked")){
                document.getElementById("id_private").setAttribute("checked", "checked");
                element.classList.remove("btn-secondary");
                element.classList.add("btn-success");
                element.innerHTML = "Private capsule";
            }else{
                document.getElementById("id_private").removeAttribute("checked");
                element.classList.remove("btn-success");
                element.classList.add("btn-secondary");
                element.innerHTML = "Public capsule";
            }
        }
        if("{{capsuleForm.deadman_switch.value}}" == "True"){
	        document.getElementById("id_private").setAttribute("checked", "checked");
	    }
        function add_deadman_switch(element){
            if(!document.getElementById("id_deadman_switch").hasAttribute("checked")){
                document.getElementById("id_deadman_switch").setAttribute("checked", "checked");
                element.classList.remove("btn-secondary");
                element.classList.add("btn-success");
                element.innerHTML = "Deadman switch activated";
            }else{
                document.getElementById("id_deadman_switch").removeAttribute("checked");
                element.classList.remove("btn-success");
                element.classList.add("btn-secondary");
                element.innerHTML = "Activate deadman switch?";
            }
            deadman_switch_activated();
        }

    </script>

    <script>
	var numberEmails = 0;
	function removeEmail(e){
		document.getElementById("email_"+e).parentNode.parentNode.remove();
	}
	
	function addEmail(){
		$("#email_inputs").append('<div class="row"><div class="col-sm-9"><input type="text" class="form-control" id="email_' + numberEmails + '" maxlength="250"></div><div class="col-sm-2"><button type="button" onclick="removeEmail('+numberEmails+')" class="btn btn-danger">Delete</button></div><br><br></div>');
		numberEmails++;
	}

	var values = "{{capsuleForm.emails.value}}";
	if(values != "None" && values != ""){
		var emails = values.split(",");

		for(var i = 0; i < emails.length; i++){
			$("#email_inputs").append('<div class="row"><div class="col-sm-9"><input type="text" class="form-control" id="email_' + i + '" value="'+$.trim(emails[i])+'" maxlength="250"></div><div class="col-sm-2"><button type="button" onclick="removeEmail('+i+')" class="btn btn-danger">Delete</button></div><br><br></div>');
			numberEmails = i;
		}
	}
	numberEmails++;

	function submitEmail(){
		var res = "";
		for(const c of document.getElementById("email_inputs").children){
			res += c.firstElementChild.firstElementChild.value + ",";
		}
		res = res.substring(0, res.length-1);
		document.getElementById("id_emails").value = res;
		console.log(document.getElementById("id_emails"));
	}
</script>


{% endblock %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styleForm.css' %}"/>
{% endblock %}

capsulefyweb/main/templates/capsule/list.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/styleList.css' %}"/>
{% endblock %}
{% block contenido %}
 <!-- Your regular body -->

<div class="container main-list">
	{% if '/list/public/' in request.path %}
  	<h3>List capsules</h3>
	{% else %}
		<h3>Your capsules</h3>
	{% endif %}

  <div class="form-group row">
		<label class="col-form-label col-sm-1" for="form_search">Search: </label>
    <div class="col-sm-11">
      <input type="text" class="form-control" name="search" id="form_search" placeholder="Search">
    </div>
  </div>


<div id="data">  
  <input id="page" type="hidden" value=""/>
</div>
</div>

<script>
	function load_capsules(page,del){
		if(del==true){
			$("#data").empty();
		}	
		$.ajax({
				url:"/ajaxlist/{{type}}",
				data: {"query":$("#form_search").val(),
						"page":page}
			}).done(function(result){
				
				
				$("#nextbt").remove()
				$("#data").append(result);
			});
	}
	$("#form_search").on('keyup', function(){
		load_capsules(1,del=true)
		
		});
	$( document ).ready(load_capsules(1))
</script>


{% endblock %}